version: '3'
services:
  # Data flow management
  node-red:
    build: ./node-red
    volumes:
      - './node-red/data:/data'
    ports:
      - '1880:1880'
    restart: on-failure

  # AMQP Broker
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5671:5671
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=qu4lity
      - RABBITMQ_DEFAULT_PASS=qu4lity
    restart: unless-stopped

  # Integrator
  wso2:
    build: ./wso2
    image: wso2/wso2ei-integrator:6.5.0
    container_name: wso2
#    volumes:
#      - './wso2/conf/carbon.xml:/home/wso2carbon/wso2ei-6.4.0/conf/carbon.xml'
    ports:
      - 8280:8280
      - 8243:8243
      - 9443:9443
